In [23]:
#Import Dependencies
import pprint as pp
import pandas as pd

In [24]:
covid_states_csv = "new_states_data.csv"
read_covid = pd.read_csv(covid_states_csv)

read_covid.dropna()
read_covid.head()

,id,date,state,positive,negative,pending,hospitalized_curr,hospitalized_cum,in_ICU_curr,in_ICU_cum,...,dontuse_total,check_date,total_tests,pos_neg,fips,death_inc,hospital_inc,neg_inc,pos_inc,tot_tests_inc
0,1,2020-04-07,AK,213,6700,0,0,23,0,0,...,6913,2020-04-07,6913,6913,2,0,0,8,22,30
1,2,2020-04-07,AL,2119,12797,0,0,271,0,0,...,14916,2020-04-07,14916,14916,1,6,31,0,151,151
2,3,2020-04-07,AR,946,12692,0,74,130,0,43,...,13638,2020-04-07,13638,13638,5,0,0,722,71,793
3,4,2020-04-07,AS,0,20,11,0,0,0,0,...,31,2020-04-07,20,20,60,0,0,0,0,0
4,5,2020-04-07,AZ,2575,30800,0,0,0,0,0,...,33375,2020-04-07,33375,33375,4,8,0,722,119,841

In [25]:
#Drop some columns
new_covid_df = read_covid[['date','state','positive']]
# new_covid_df = pd.to_datetime(read_covid['date'],format='%Y%m%d')
new_covid_df

            date state  positive
0     2020-04-07    AK       213
1     2020-04-07    AL      2119
2     2020-04-07    AR       946
3     2020-04-07    AS         0
4     2020-04-07    AZ      2575
...          ...   ...       ...
1816  2020-03-04    OR         3
1817  2020-03-04    SC         0
1818  2020-03-04    TX         1
1819  2020-03-04    WA        39
1820  2020-03-04    WI         1

[1821 rows x 3 columns]

In [26]:
date_list = []
for i in new_covid_df:
    date_list.append(i)
    print(i)

date
state
positive

In [27]:
# date_dict = {'state': read_covid['state'],'date': read_covid['date'] ,'formatted_date':date_list,'total': read_covid['total']}

# date_df = pd.DataFrame(date_dict)
# date_df = date_df.fillna(0)
# int_date = date_df.date.astype(int)
# int_values = date_df.total.astype(int)

# new_date_dict = {'state': read_covid['state'],'date': int_date ,'formatted_date': date_list,'total': int_values}
# new_date_df = pd.DataFrame(new_date_dict)
# new_date_df

# df_group = new_date_df.groupby(['state','date'])
# state_total = df_group['total'].sum()
# state_dict = {'total':state_total}
# df = pd.DataFrame(state_dict).reset_index()
# df = df.dropna(0)
# df.max()

In [28]:
# df.to_csv("states_total.csv", index=False)
# new_date_df.to_csv("non_pivot_states.csv", index=False)

In [29]:
# covid_states_pivot = date_df.pivot(index='state',values='total',columns='formatted_date')
covid_states_pivot = new_covid_df.pivot(index='state',values='positive',columns='date')

In [30]:
covid_states_pivot.reset_index()

date,state,2020-03-04,2020-03-05,2020-03-06,2020-03-07,2020-03-08,2020-03-09,2020-03-10,2020-03-11,2020-03-12,...,2020-03-29,2020-03-30,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-04,2020-04-05,2020-04-06,2020-04-07
0,AK,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,102.0,114.0,119.0,133.0,143.0,157.0,171.0,185.0,191.0,213.0
1,AL,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,806.0,859.0,981.0,1077.0,1233.0,1432.0,1580.0,1796.0,1968.0,2119.0
2,AR,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,426.0,473.0,523.0,584.0,643.0,704.0,743.0,830.0,875.0,946.0
3,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AZ,2.0,2.0,3.0,5.0,5.0,5.0,6.0,9.0,9.0,...,919.0,1157.0,1289.0,1413.0,1598.0,1769.0,2019.0,2269.0,2456.0,2575.0
5,CA,53.0,53.0,60.0,69.0,88.0,114.0,133.0,157.0,202.0,...,5708.0,6447.0,7482.0,8155.0,9191.0,10701.0,12026.0,13438.0,14336.0,15865.0
6,CO,NaN,0.0,2.0,8.0,8.0,9.0,12.0,28.0,45.0,...,2061.0,2627.0,2627.0,2966.0,3342.0,3728.0,4173.0,4565.0,4950.0,5172.0
7,CT,NaN,NaN,NaN,0.0,1.0,1.0,2.0,3.0,6.0,...,1993.0,2571.0,3128.0,3557.0,3824.0,4914.0,5276.0,5675.0,6906.0,7781.0
8,DC,NaN,0.0,0.0,0.0,1.0,1.0,5.0,5.0,10.0,...,342.0,401.0,495.0,586.0,653.0,757.0,902.0,998.0,1097.0,1211.0
9,DE,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,4.0,...,232.0,264.0,319.0,368.0,393.0,450.0,593.0,673.0,673.0,928.0
10,FL,2.0,9.0,9.0,14.0,17.0,18.0,19.0,28.0,32.0,...,4246.0,5473.0,6338.0,6955.0,8010.0,9585.0,11111.0,12151.0,13324.0,14747.0
11,GA,2.0,2.0,2.0,6.0,7.0,12.0,17.0,22.0,31.0,...,2651.0,2809.0,3929.0,4638.0,5348.0,5831.0,6160.0,6647.0,7314.0,8818.0
12,GU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.0,58.0,69.0,77.0,82.0,84.0,93.0,112.0,113.0,121.0
13,HI,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,...,151.0,175.0,204.0,208.0,258.0,285.0,319.0,351.0,371.0,387.0
14,IA,NaN,NaN,0.0,0.0,0.0,3.0,8.0,13.0,14.0,...,336.0,424.0,497.0,549.0,614.0,699.0,786.0,868.0,946.0,1048.0
15,ID,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,261.0,310.0,415.0,525.0,669.0,891.0,1013.0,1077.0,1101.0,1170.0
16,IL,4.0,5.0,5.0,6.0,6.0,7.0,19.0,19.0,25.0,...,4596.0,5057.0,5994.0,6980.0,7695.0,8904.0,10357.0,11256.0,12262.0,13549.0
17,IN,NaN,NaN,1.0,1.0,2.0,2.0,6.0,10.0,12.0,...,1514.0,1786.0,2159.0,2565.0,3039.0,3437.0,3953.0,4411.0,4944.0,5507.0
18,KS,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0,4.0,...,319.0,368.0,428.0,482.0,552.0,620.0,698.0,747.0,845.0,900.0
19,KY,NaN,NaN,0.0,1.0,1.0,4.0,6.0,8.0,8.0,...,394.0,439.0,480.0,591.0,680.0,770.0,831.0,917.0,955.0,1008.0
20,LA,NaN,NaN,NaN,0.0,0.0,1.0,1.0,6.0,14.0,...,3540.0,4025.0,5237.0,6424.0,9150.0,10297.0,12496.0,13010.0,14867.0,16284.0
21,MA,2.0,2.0,8.0,13.0,13.0,41.0,92.0,92.0,95.0,...,4955.0,5752.0,6620.0,7738.0,8966.0,10402.0,11736.0,12500.0,13837.0,15202.0
22,MD,NaN,0.0,3.0,3.0,3.0,5.0,6.0,9.0,12.0,...,1239.0,1413.0,1660.0,1985.0,2331.0,2758.0,3125.0,3609.0,4045.0,4371.0
23,ME,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,...,253.0,275.0,303.0,344.0,376.0,432.0,456.0,470.0,499.0,519.0
24,MI,NaN,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,...,5486.0,6498.0,7615.0,9334.0,10791.0,12744.0,14225.0,15718.0,17221.0,18970.0
25,MN,NaN,NaN,0.0,1.0,1.0,2.0,3.0,5.0,9.0,...,503.0,576.0,629.0,689.0,742.0,789.0,865.0,935.0,986.0,1069.0
26,MO,NaN,NaN,NaN,0.0,1.0,1.0,1.0,1.0,1.0,...,838.0,1031.0,1327.0,1581.0,1834.0,2113.0,2291.0,2367.0,2722.0,3037.0
27,MP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2.0,2.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0
28,MS,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,...,758.0,847.0,937.0,1073.0,1177.0,1358.0,1455.0,1638.0,1738.0,1915.0
29,MT,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,...,154.0,171.0,184.0,208.0,227.0,243.0,265.0,286.0,299.0,319.0
30,NC,1.0,1.0,2.0,2.0,2.0,2.0,7.0,7.0,12.0,...,1040.0,1307.0,1498.0,1584.0,1857.0,2093.0,2402.0,2585.0,2870.0,3221.0
31,ND,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,...,98.0,109.0,126.0,142.0,159.0,173.0,186.0,207.0,225.0,237.0
32,NE,NaN,0.0,0.0,1.0,1.0,3.0,3.0,5.0,10.0,...,108.0,145.0,172.0,210.0,246.0,279.0,321.0,363.0,409.0,447.0
33,NH,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,6.0,...,214.0,314.0,314.0,415.0,415.0,479.0,540.0,621.0,669.0,715.0
34,NJ,NaN,1.0,1.0,4.0,6.0,11.0,15.0,24.0,30.0,...,13386.0,16636.0,18696.0,22255.0,25590.0,29895.0,34124.0,37505.0,41090.0,44416.0
35,NM,NaN,NaN,0.0,0.0,0.0,0.0,0.0,3.0,5.0,...,237.0,237.0,281.0,315.0,363.0,403.0,495.0,543.0,624.0,686.0
36,NV,NaN,1.0,1.0,1.0,1.0,1.0,0.0,5.0,7.0,...,738.0,1008.0,1113.0,1279.0,1458.0,1514.0,1742.0,1836.0,1953.0,2087.0
37,NY,6.0,22.0,33.0,76.0,105.0,142.0,173.0,216.0,216.0,...,59513.0,66497.0,75795.0,83712.0,92381.0,102863.0,113704.0,122031.0,130689.0,138863.0
38,OH,NaN,0.0,0.0,0.0,0.0,3.0,3.0,4.0,5.0,...,1653.0,1933.0,2199.0,2547.0,2902.0,3312.0,3739.0,4043.0,4450.0,4782.0
39,OK,NaN,NaN,NaN,1.0,1.0,1.0,2.0,2.0,3.0,...,429.0,481.0,565.0,719.0,879.0,988.0,1159.0,1252.0,1327.0,1472.0
40,OR,3.0,3.0,3.0,7.0,14.0,14.0,15.0,19.0,19.0,...,548.0,606.0,690.0,736.0,826.0,899.0,899.0,999.0,1068.0,1132.0
41,PA,NaN,NaN,2.0,2.0,4.0,7.0,12.0,15.0,22.0,...,3394.0,4087.0,4843.0,5805.0,7016.0,8420.0,10017.0,11510.0,12980.0,14559.0
42,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,127.0,174.0,239.0,286.0,316.0,378.0,452.0,475.0,513.0,573.0
43,RI,NaN,NaN,NaN,2.0,3.0,3.0,3.0,5.0,5.0,...,294.0,408.0,488.0,566.0,657.0,711.0,806.0,922.0,1082.0,1229.0
44,SC,0.0,0.0,0.0,2.0,2.0,7.0,7.0,9.0,10.0,...,774.0,925.0,1083.0,1293.0,1554.0,1554.0,1917.0,2049.0,2049.0,2417.0
45,SD,NaN,NaN,NaN,0.0,0.0,0.0,0.0,5.0,8.0,...,90.0,101.0,108.0,129.0,165.0,187.0,212.0,240.0,288.0,320.0
46,TN,NaN,1.0,1.0,1.0,3.0,3.0,7.0,7.0,18.0,...,1537.0,1834.0,2239.0,2683.0,2845.0,3067.0,3321.0,3633.0,3802.0,4138.0
47,TX,1.0,1.0,5.0,8.0,8.0,12.0,13.0,21.0,23.0,...,2552.0,2877.0,3266.0,3997.0,4669.0,5330.0,6110.0,6812.0,7276.0,8262.0
48,UT,NaN,NaN,NaN,1.0,1.0,1.0,2.0,2.0,4.0,...,719.0,806.0,887.0,1012.0,1074.0,1246.0,1428.0,1605.0,1675.0,1738.0
49,VA,NaN,0.0,0.0,0.0,2.0,3.0,8.0,9.0,17.0,...,890.0,1020.0,1250.0,1484.0,1706.0,2012.0,2407.0,2637.0,2878.0,3333.0
50,VI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.0,30.0,30.0,30.0,33.0,38.0,40.0,42.0,43.0,43.0
51,VT,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0,2.0,...,235.0,256.0,293.0,321.0,338.0,389.0,461.0,512.0,543.0,575.0
52,WA,39.0,70.0,79.0,102.0,102.0,136.0,162.0,267.0,337.0,...,4310.0,4896.0,4896.0,5634.0,5984.0,6585.0,6966.0,7591.0,7984.0,8384.0
53,WI,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,8.0,...,1112.0,1221.0,1351.0,1550.0,1730.0,1912.0,2112.0,2267.0,2440.0,2578.0
54,WV,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,113.0,126.0,162.0,191.0,217.0,237.0,282.0,324.0,345.0,412.0
55,WY,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,...,86.0,94.0,109.0,130.0,150.0,162.0,187.0,197.0,210.0,216.0

In [31]:
covid_states_pivot.to_csv('clean_covid_states.csv')